<?php

namespace Flyers\PlanITBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ChargeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChargeRepository extends EntityRepository
{
}
