<?php
$title = 'Edit album';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('album', array('action'=>'index'));?>">Back</a>
</p>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
								'album', 
								array(
									'id'     => $this->id,
									'action' => 'edit', 
									)
					));
$form->prepare();

echo $this->form()->openTag($form);

$album = $form->get('album');

echo $this->formHidden($album->get('id'));
echo $this->formRow($album->get('title'));
echo $this->formRow($album->get('artist'));
echo $this->formHidden($form->get('security'));
echo $this->formSubmit($form->get('submit'));

echo $this->form()->closeTag();